### PR TITLE
first draft; NB I'm not sure I got the test syntax correct because my…

### PR DESCRIPTION
**Pull request by guyardito**
… testing/usage pattern needs are a little different from the example provided.

### CODE REVIEW

**Comment by JimCampagno** [comment]
I like the idea of this having more questions with more tests. Something like the following:

**1** - Create a function named `averageIsAbove75` that takes in three arguments all of type `Double` with a return type of type `Bool`. Create this function in the `ViewController.swift` file located in the .xcworkspace file included with this repo. Create this function in that file below where you see the following comment:

``` swift
    // Implement your functions here
```

 If you were to call on this function, it would yield the following results:

``` swift
averageIsAbove75(55, 25, 24)
// false

averageIsAbove75(100, 85, 90)
// true
```

Answer to the above question (tests would need to be written for this).

``` swift
func averageIsAbove75(a: Double, _ b: Double, _ c: Double) -> Bool {
    let avg = (a + b + c) / 3
    return avg > 75
}
```

---

**2** - Create a function named `passwordCombo` that takes in two arguments, one of type `String` which represents the username and the other of type `Int` which represents the password. This function will return a `String` letting the caller of this function know if the username/password combo passed into the function is correct!

What makes it correct? The conditions are.. the username `String` must be either 'Jerry', 'Elane', or 'Michael'. The password must be divisible by 3. If the username + password conditions pass, then return back the `String` "Welcome!". If either or both fail, then the `String` to be returned should be "Access Denied"

Calling this function should yield the following results:

``` swift
passwordCombo(username: "Bran", password: 22)
// "Access Denied

passwordCombo(username: "Elane", password: 20)
// "Access Denied"

passwordCombo(username: "Elane", password: 33)
// "Welcome!"
```

Answer to the above question (tests would need to be written for this).

``` swift
func passwordCombo(username username: String, password: Int) -> String {
    switch username {
    case "Jerry", "Elane", "Michael":

        if password % 3 == 0 {
            return "Welcome!"
        } else {
            return "Access Denied"
        }

    default: return "Access Denied"
    }
}
```

---

**REGARDING YOUR QUESTION**:

I like your question, but considering that the student doesn't know about Optionals yet (which they would have to know here.. considering they would be converting a `String` to a `Float`), I would prefer to have both arguments to the function you're asking them to make be of type `Double`, asking the question in a similar format to how I presented it above. Maybe have your question be the 3rd one here.. considering it's more difficult, unless you think they should be asked in a different order.

@guyardito

**Comment by guyardito** [comment]
Hey Jim

A few points:
1. I can add those
2. the solution to my problem doesn't require optionals; a 'switch' is used to test the values of the string arg (which is in the range 1..5); if it's out of range then it returns 0.   No optional required.  :)
3. I'm not clear where in the repository you want a sample solution to the problem(s)

**Comment by guyardito** [comment]
Jim, I still haven't gotten word from you as to where to put the sample solutions to the coding challenges.  Please advise.  :)

**Comment by guyardito** [comment]
@JimCampagno    Jim, I'm not sure if you noticed my past couple of comments because I didn't explicitly tag you, so I'm tagging you here.  :)

**Comment by JimCampagno** [comment]
I just got a chance to go through this. These changes are really good! I like the formatting of the 3rd question. Yea.. I see what you mean in your second point by not using optionals, I was at first doing this:

``` swift
func doIt(a: String, b: Float) -> Float {

    var first: Float = 0.0
    var second: Float = 0.0

    switch a {
    case "1", "2", "3", "4", "5": first = Float(a)!
    default: return 0.0
    }

    switch b {
    case 10.5...15.0: second = b
    case 20.0...30.5: second = b
    default: return 0.0
    }

    return first * second
}

let a = doIt("2", b: 10.5) // 21
let b = doIt("9", b: 10.5) // 0
let c = doIt("2", b: 7) // 0
```

That all being said. Your next stops are as follows.

Create a separate branch off of _YOUR_ master branch. I usually do this in terminal typing the following command:
`git checkout -b solution`

You can then checkout between branches by typing
`git checkout master` to get back to master
`git checkout solution` to get back to your solution branch

That solution branch should contain the answers to the questions above where the students are being asked to implement the functions. The master branch should be empty and ready for the students to begin work!

I can be more explicit with what I wrote above if you like. If it's not going smoothly on your end (don't drive ourself nuts! I'm here to help.) You can instead provide the answers to the three questions above here and I will put it together.

Oh.. when you make this separate branch named 'solution' on your end, I _think_ you have to do a pull request for that separate branch.

Overall, good stuff!! 👍 If I don't hear from you, have a great 4th.

@guyardito

**Comment by guyardito** [comment]
@JimCampagno 

Jim, I followed the instructions above but github isn't showing the branch, which I'm _assuming_ I need to switch to before doing a pull.  It also looks like I got some error.  Please clarify.  :)

NB  here's my Terminal history:

Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ ls -l
total 40
drwxr-xr-x  7 Guy  staff   238 Jun 29 14:32 AllTheBasics
drwxr-xr-x  5 Guy  staff   170 Jun 29 14:36 AllTheBasics.xcodeproj
drwxr-xr-x  4 Guy  staff   136 Jun 29 14:36 AllTheBasics.xcworkspace
drwxr-xr-x  4 Guy  staff   136 Jul  1 10:13 AllTheBasicsTests
-rw-r--r--  1 Guy  staff  1809 Jun 29 14:32 CONTRIBUTING.md
-rw-r--r--  1 Guy  staff  1347 Jun 29 14:32 LICENSE.md
-rw-r--r--  1 Guy  staff   392 Jun 29 14:32 Podfile
-rw-r--r--  1 Guy  staff   293 Jun 29 14:32 Podfile.lock
drwxr-xr-x  7 Guy  staff   238 Jul  1 09:58 Pods
-rw-r--r--@ 1 Guy  staff  2875 Jul  1 22:22 README.md
Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ git checkout -b solution
M   .DS_Store
M   README.md
Switched to a new branch 'solution'
Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ ls -l
total 48
drwxr-xr-x  7 Guy  staff   238 Jun 29 14:32 AllTheBasics
drwxr-xr-x  5 Guy  staff   170 Jun 29 14:36 AllTheBasics.xcodeproj
drwxr-xr-x  4 Guy  staff   136 Jun 29 14:36 AllTheBasics.xcworkspace
drwxr-xr-x  4 Guy  staff   136 Jul  1 10:13 AllTheBasicsTests
-rw-r--r--  1 Guy  staff  1809 Jun 29 14:32 CONTRIBUTING.md
-rw-r--r--  1 Guy  staff  1347 Jun 29 14:32 LICENSE.md
-rw-r--r--  1 Guy  staff   392 Jun 29 14:32 Podfile
-rw-r--r--  1 Guy  staff   293 Jun 29 14:32 Podfile.lock
drwxr-xr-x  7 Guy  staff   238 Jul  1 09:58 Pods
-rw-r--r--@ 1 Guy  staff  4237 Jul  1 22:35 README.md
Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ git add .
Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ git commit -m "added solutins to the README in this branch"
[solution 35053ed] added solutins to the README in this branch
 Committer: Guy Ardito Guy@Guys-MBP.home
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

```
git config --global --edit
```

After doing this, you may fix the identity used for this commit with:

```
git commit --amend --reset-author
```

 2 files changed, 95 insertions(+), 6 deletions(-)
Guys-MBP:swift-mathBoolOpConSwitch-lab Guy$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: The current branch solution has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin solution
```

**Comment by JimCampagno** [comment]
Hmm. Interesting. I'm going to _merge_ this in and produce this solution branch now. So nothing further needs to be done on your end with this lab. 👍 

@guyardito

**Comment by guyardito** [comment]
@JimCampagno 

OK

_BUT_  is there anything I need to do regarding maintenance / housekeeping / synchronization / etc. because of the branch I created locally?

**Comment by JimCampagno** [comment]
Nope, all good!

@guyardito

**Pull request merged**
